import type { CalendarItem, EmailMessage } from './types'
import { DEFAULT_CATEGORIES } from './categories'

function catColour(id: string): string {
  return DEFAULT_CATEGORIES.find((c) => c.id === id)?.colour ?? '#8E8E93'
}

export const initialItems: CalendarItem[] = [
  {
    id: '1',
    title: 'Julie Holiday',
    date: '2026-06-23',
    endDate: '2026-06-27',
    allDay: true,
    categoryId: 'holiday',
    colour: catColour('holiday'),
    notes: 'Annual leave',
  },
  {
    id: '2',
    title: 'Pay VAT',
    date: '2026-06-23',
    allDay: true,
    categoryId: 'work',
    colour: catColour('work'),
    notes: 'Quarterly VAT return due',
  },
  {
    id: '3',
    title: 'Client meeting',
    date: '2026-06-23',
    startTime: '09:00',
    endTime: '10:30',
    allDay: false,
    categoryId: 'appointment',
    colour: catColour('appointment'),
    notes: 'Review Q2 deliverables with Acme Corp',
  },
  {
    id: '4',
    title: 'Dentist',
    date: '2026-06-23',
    startTime: '13:30',
    endTime: '14:15',
    allDay: false,
    categoryId: 'personal',
    colour: catColour('personal'),
  },
  {
    id: '5',
    title: 'Order steel',
    date: '2026-06-24',
    allDay: true,
    categoryId: 'work',
    colour: catColour('work'),
    notes: 'Confirm delivery with supplier',
  },
  {
    id: '6',
    title: 'Site visit',
    date: '2026-06-24',
    startTime: '10:00',
    endTime: '12:00',
    allDay: false,
    categoryId: 'work',
    colour: catColour('work'),
  },
  {
    id: '7',
    title: 'Pick up feed',
    date: '2026-06-24',
    startTime: '16:00',
    endTime: '16:30',
    allDay: false,
    categoryId: 'personal',
    colour: catColour('personal'),
  },
  {
    id: '8',
    title: 'Team standup',
    date: '2026-06-25',
    startTime: '09:30',
    endTime: '10:00',
    allDay: false,
    categoryId: 'work',
    colour: catColour('work'),
  },
  {
    id: '9',
    title: 'Send invoice to Henderson',
    date: '2026-06-25',
    allDay: false,
    categoryId: 'task',
    colour: catColour('task'),
    completed: false,
  },
  {
    id: '10',
    title: 'School sports day',
    date: '2026-06-25',
    startTime: '14:00',
    endTime: '16:00',
    allDay: false,
    categoryId: 'family',
    colour: catColour('family'),
  },
  {
    id: '11',
    title: 'Review project brief',
    date: '2026-06-26',
    allDay: false,
    categoryId: 'reminder',
    colour: catColour('reminder'),
    completed: false,
  },
  {
    id: '12',
    title: 'Lunch with Sarah',
    date: '2026-06-26',
    startTime: '12:30',
    endTime: '13:30',
    allDay: false,
    categoryId: 'personal',
    colour: catColour('personal'),
  },
  {
    id: '13',
    title: 'Board presentation prep',
    date: '2026-06-26',
    startTime: '15:00',
    endTime: '17:00',
    allDay: false,
    categoryId: 'work',
    colour: catColour('work'),
  },
  {
    id: '14',
    title: 'Bank holiday weekend',
    date: '2026-06-27',
    endDate: '2026-06-29',
    allDay: true,
    categoryId: 'holiday',
    colour: catColour('holiday'),
  },
  {
    id: '15',
    title: 'Garden centre',
    date: '2026-06-27',
    startTime: '11:00',
    endTime: '12:00',
    allDay: false,
    categoryId: 'family',
    colour: catColour('family'),
  },
  {
    id: '16',
    title: 'Call Mum',
    date: '2026-06-28',
    allDay: false,
    categoryId: 'reminder',
    colour: catColour('reminder'),
    completed: false,
  },
  {
    id: '17',
    title: 'Weekly planning',
    date: '2026-06-29',
    startTime: '08:00',
    endTime: '08:30',
    allDay: false,
    categoryId: 'work',
    colour: catColour('work'),
  },
  {
    id: '18',
    title: 'Car MOT reminder',
    date: '2026-06-29',
    allDay: false,
    categoryId: 'reminder',
    colour: catColour('reminder'),
    completed: false,
  },
  {
    id: '19',
    title: 'Design review',
    date: '2026-06-30',
    startTime: '11:00',
    endTime: '12:00',
    allDay: false,
    categoryId: 'appointment',
    colour: catColour('appointment'),
  },
  {
    id: '20',
    title: 'Quarterly accounts',
    date: '2026-07-01',
    allDay: true,
    categoryId: 'work',
    colour: catColour('work'),
  },
]

export const initialEmails: EmailMessage[] = [
  {
    id: 'e1',
    accountId: 'work-outlook',
    folderId: 'work-clients',
    from: 'Acme Corp',
    fromEmail: 'projects@acme.com',
    subject: 'Re: Q2 deliverables review',
    preview: 'Thanks for sending the updated timeline. We can confirm the meeting for Tuesday at 9am…',
    body: 'Hi,\n\nThanks for sending the updated timeline. We can confirm the meeting for Tuesday at 9am.\n\nPlease bring the revised cost breakdown and milestone chart.\n\nBest,\nJames Mitchell\nProject Director, Acme Corp',
    date: '2026-06-23T08:15:00',
    unread: true,
    starred: true,
    flagged: false,
    category: 'Work',
    labels: ['Clients', 'Important'],
  },
  {
    id: 'e2',
    accountId: 'work-outlook',
    folderId: 'work-finance',
    from: 'HMRC',
    fromEmail: 'noreply@hmrc.gov.uk',
    subject: 'VAT return reminder — due 23 June',
    preview: 'Your VAT return for the period ending 31 May 2026 is due today. Please submit…',
    body: 'Dear taxpayer,\n\nYour VAT return for the period ending 31 May 2026 is due today.\n\nPlease submit your return and payment through your online account.\n\nHM Revenue & Customs',
    date: '2026-06-23T07:00:00',
    unread: true,
    starred: false,
    flagged: true,
    category: 'Finance',
    labels: ['Tax', 'Urgent'],
  },
  {
    id: 'e3',
    accountId: 'personal-gmail',
    folderId: 'personal-inbox',
    from: 'Sarah Chen',
    fromEmail: 'sarah.chen@gmail.com',
    subject: 'Lunch Thursday?',
    preview: 'Hey! Are we still on for lunch at The Willow on Thursday? I can do 12:30…',
    body: 'Hey!\n\nAre we still on for lunch at The Willow on Thursday? I can do 12:30 if that works for you.\n\nLet me know!\nSarah x',
    date: '2026-06-22T18:42:00',
    unread: false,
    starred: true,
    flagged: false,
    category: 'Personal',
    labels: ['Friends'],
  },
  {
    id: 'e4',
    accountId: 'work-outlook',
    folderId: 'work-inbox',
    from: 'Steel Supplies Ltd',
    fromEmail: 'orders@steelsupplies.co.uk',
    subject: 'Order confirmation #SS-44821',
    preview: 'Your order has been confirmed for delivery on 25 June. Total: £2,340.00…',
    body: 'Dear Customer,\n\nYour order #SS-44821 has been confirmed.\n\nDelivery date: 25 June 2026\nTotal: £2,340.00\n\nThank you for your business.\nSteel Supplies Ltd',
    date: '2026-06-22T14:20:00',
    unread: false,
    starred: false,
    flagged: false,
    category: 'Work',
    labels: ['Suppliers'],
  },
  {
    id: 'e5',
    accountId: 'family-icloud',
    folderId: 'family-school',
    from: 'Oakwood Primary',
    fromEmail: 'office@oakwoodprimary.sch.uk',
    subject: 'Sports Day — Wednesday 25 June',
    preview: 'Reminder: Sports Day is this Wednesday. Children should arrive in PE kit…',
    body: 'Dear Parents,\n\nReminder: Sports Day is this Wednesday, 25 June.\n\nChildren should arrive in PE kit with a water bottle and sun hat.\n\nParents welcome from 2pm on the lower field.\n\nOakwood Primary School',
    date: '2026-06-21T09:00:00',
    unread: true,
    starred: false,
    flagged: false,
    category: 'Family',
    labels: ['School'],
  },
  {
    id: 'e6',
    accountId: 'personal-gmail',
    folderId: 'personal-social',
    from: 'LinkedIn',
    fromEmail: 'messages-noreply@linkedin.com',
    subject: 'You have 3 new connection requests',
    preview: 'See who wants to connect with you on LinkedIn…',
    body: 'You have 3 new connection requests.\n\nView your pending invitations on LinkedIn.',
    date: '2026-06-20T16:30:00',
    unread: false,
    starred: false,
    flagged: false,
    category: 'Social',
    labels: ['Notifications'],
  },
  {
    id: 'e7',
    accountId: 'work-outlook',
    folderId: 'work-inbox',
    from: 'Design Studio',
    fromEmail: 'hello@designstudio.io',
    subject: 'Updated brand guidelines attached',
    preview: 'Please find attached the revised brand guidelines for the WeekFlow project…',
    body: 'Hi,\n\nPlease find attached the revised brand guidelines for the WeekFlow project.\n\nKey changes:\n- Updated colour palette\n- New typography scale\n- Icon set v2\n\nLet us know if you have any questions.\n\nDesign Studio',
    date: '2026-06-20T11:15:00',
    unread: false,
    starred: true,
    flagged: false,
    category: 'Work',
    labels: ['Design', 'Projects'],
  },
  {
    id: 'e8',
    accountId: 'personal-gmail',
    folderId: 'personal-inbox',
    from: 'British Gas',
    fromEmail: 'billing@britishgas.co.uk',
    subject: 'Your energy bill — £142.50 due 30 June',
    preview: 'Your latest energy bill is ready. Amount due: £142.50. Payment due by 30 June 2026…',
    body: 'Dear Customer,\n\nYour latest energy bill is ready to view.\n\nAccount: ****4521\nAmount due: £142.50\nDue date: 30 June 2026\n\nPlease pay by the due date to avoid late fees. Your bill PDF is attached.\n\nBritish Gas',
    date: '2026-06-23T09:30:00',
    unread: true,
    starred: false,
    flagged: true,
    category: 'Finance',
    labels: ['Bills', 'Urgent'],
  },
]

export const EMAIL_CATEGORIES = ['All', 'Work', 'Finance', 'Personal', 'Family', 'Social']

export const MOCK_EMAIL_ACCOUNTS = [
  {
    id: 'work-outlook',
    label: 'Work',
    email: 'angi@asfabs.co.uk',
    provider: 'Outlook',
    colour: '#0078d4',
  },
  {
    id: 'personal-gmail',
    label: 'Personal',
    email: 'angi@gmail.com',
    provider: 'Gmail',
    colour: '#ea4335',
  },
  {
    id: 'family-icloud',
    label: 'Family',
    email: 'family@icloud.com',
    provider: 'iCloud',
    colour: '#555555',
  },
] as const

export const MOCK_EMAIL_FOLDERS = [
  { id: 'work-inbox', label: 'Inbox', accountId: 'work-outlook' },
  { id: 'work-clients', label: 'Clients', accountId: 'work-outlook' },
  { id: 'work-finance', label: 'Finance', accountId: 'work-outlook' },
  { id: 'personal-inbox', label: 'Inbox', accountId: 'personal-gmail' },
  { id: 'personal-social', label: 'Social', accountId: 'personal-gmail' },
  { id: 'family-inbox', label: 'Inbox', accountId: 'family-icloud' },
  { id: 'family-school', label: 'School', accountId: 'family-icloud' },
] as const

export function getEmailAccount(accountId: string) {
  return MOCK_EMAIL_ACCOUNTS.find((account) => account.id === accountId)
}

export function getEmailFolder(folderId: string) {
  return MOCK_EMAIL_FOLDERS.find((folder) => folder.id === folderId)
}

export const MOCK_CLOUD_FOLDERS = [
  {
    id: 'folder-bills-2026',
    label: 'OneDrive / Bills / 2026',
    path: '/Documents/Bills/2026',
    provider: 'OneDrive',
    url: 'https://onedrive.live.com/mock/Bills/2026',
  },
  {
    id: 'folder-finance-vat',
    label: 'OneDrive / Finance / VAT',
    path: '/Documents/Finance/VAT',
    provider: 'OneDrive',
    url: 'https://onedrive.live.com/mock/Finance/VAT',
  },
  {
    id: 'folder-household',
    label: 'OneDrive / Household',
    path: '/Documents/Household',
    provider: 'OneDrive',
    url: 'https://onedrive.live.com/mock/Household',
  },
] as const

export function getMockCloudFolder(folderId: string) {
  return MOCK_CLOUD_FOLDERS.find((folder) => folder.id === folderId)
}
